De basis van de class aflegstapel is gemaakt
JarkoDubbeldam/Evolution pull request #2
Opened 2018-11-01 17:04 UTC by MariskaOudshoorn

2018-11-01 17:04 UTC, MariskaOudshoorn commented
https://github.com/JarkoDubbeldam/Evolution/projects/1#card-14319393

2018-11-01 17:09 UTC, JarkoDubbeldam commented
#3

2018-11-01 17:34 UTC, JarkoDubbeldam requested changes

2018-11-01 17:34 UTC, JarkoDubbeldam commented on EvolutionModel/Aflegstapel.cs
> + * Er zijn twee mogelijkheden, of je verplaatst alle kaarten naar het deck, of je refresht het deck en leegt de aflegstapel.
We willen de kaarten verplaatsen. Het deck moet namelijk diezelfde kaarten krijgen die in de aflegstapel liggen. Niet meer, niet minder. De kaarten die in het spel zijn blijven daar en moeten niet gedupliceerd worden.

Het deck weet niet welke kaarten er in de aflegstapel zitten.

2018-11-06 07:51 UTC, JarkoDubbeldam commented on EvolutionModelTests/AflegstapelTests.cs
> +      var cards = Enumerable.Range(0, 5).Select(x => new Card());
Ik maak hier een sequence (IEnumerable<Card>) van 5 kaarten. Later vergelijk ik die met de kaarten die gereturnd worden.

`Range` is een static method in de class `Enumerable`. Die neemt 2 argumenten, een beginwaarde en de lengte. Wat er gereturnd wordt is een sequence met die eigenschappen. In dit geval dus `0, 1, 2, 3, 4`. `Select` maakt voor elk element in die sequence een nieuwe kaart aan. Uiteindelijk hebben we dus 5 kaarten.

2018-11-06 07:52 UTC, JarkoDubbeldam commented on EvolutionModelTests/AflegstapelTests.cs
> +        // Check that each card is present in the returned set of cards.
De volgorde van de kaarten boeit ons niet. Het gaat er alleen om dat alle kaarten erin zitten, een keer.

2018-11-06 10:27 UTC, JarkoDubbeldam requested changes
Nog niet af geloof ik :smile:

2018-11-06 10:27 UTC, JarkoDubbeldam commented on EvolutionModel/Aflegstapel.cs
> +       var tijdelijkdeck = new Aflegstapel();
Moet er een nieuwe aflegstapel gemaakt worden? Op het moment dat je de aflegstapel leegt (functioneel gezien), maak je niet eerst een nieuwe stapel, maar je pakt enkel de kaarten en plaatst die geschud weer in de trekstapel. We zijn niet geinteresseerd in wat de rest van de aflegstapel te bieden heeft, enkel in welke kaarten er precies in zaten.

(Vandaar ook dat de method `IEnumerable<Card>` returnt, in plaats van `Aflegstapel`. We willen een sequence/collectie van kaarten teruggeven, en in welke volgorde of in welk format precies maakt ons niet super veel uit.

2018-11-06 10:27 UTC, JarkoDubbeldam commented on EvolutionModel/Aflegstapel.cs
>      }
Er wordt hier nog niets gereturnt. Dat vindt de compiler ok als de method eindigt in een exception, zoals `throw new NotImplementedException();`, maar anders begint hij te gillen. Als je dus nog niet zeker weet wat je precies wilt/kunt returnen kan je op zich de exception laten staan.

2018-11-06 17:28 UTC, JarkoDubbeldam submitted a review, later dismissed
Okidoki

2018-11-08 19:53 UTC, JarkoDubbeldam approved these changes
Okidoki

2018-11-12 12:00 UTC, merged